/// Generated by AssetsRefGenerator on 2021/07/01
class Res {
  static const String television = "assets/icons/television.png";
  static const String enter_mobile_number = "assets/images/enter_mobile_number.png";
  static const String failed = "assets/images/failed.png";
  static const String otp = "assets/images/otp.png";
  static const String splash_image = "assets/images/splash_image.png";
  static const String verified = "assets/images/verified.png";
  static const String loading = "assets/lottie/loading.json";
  static const String sending_sms = "assets/lottie/sending_sms.json";
}
